### ISSUE TITLE
Checkstyle config Getter/Setter

### ISSUE THREAD

**Issue by darenegade** [uhafner/codingstyle#1]
Its common to allow a missing JavaDoc on an accessor method.

I would recommend to edit the checkstyle_configuration.xml to:
``` xml
....
    <module name="JavadocMethod">
      <property name="scope" value="protected"/>
      <property name="allowUndeclaredRTE" value="true"/>
      <property name="allowMissingPropertyJavadoc" value="true"/>
    </module>
...
```

**Comment by uhafner** [comment]
Well, if the property itself is described (or has a meaningful name), then it makes sense to have no comment. (According to Uncle Bob (http://blog.cleancoder.com) there are only some rare conditions where a comment makes sense at all.)  

However, most novice programmers fail here (this style guide is for beginners): I find so many poor property names in practice so this is the reason I still have this rule active (at least for beginners;-) Feel free to weaken the rules if you know what you are doing...
